/**
 * @bookId 图书ID string
 * @bookName 图书名 string
 * @isBook 是否预定 boolean
 * @isBorrow 是否借阅 boolean
 * @author 作者 string
 */
 export interface bookType
 {
     bookId:string, 
     bookName:string,
     isBook:boolean,
     isBorrow:boolean,
     author:string,
 }
 
 export const bookStore:bookType[] = [
     {
         bookId:'001', 
         bookName:'诗经',
         isBook:false,
         isBorrow:false,
         author:'佚名',
     },
     {
         bookId:'002', 
         bookName:'山海经',
         isBook:false,
         isBorrow:false,
         author:'大禹'
     },
     {
         bookId:'003', 
         bookName:'资治通鉴',
         isBook:false,
         isBorrow:false,
         author:'司马光'
     },
     {
         bookId:'004', 
         bookName:'苏东坡传',
         isBook:false,
         isBorrow:false,
         author:'林语堂'
     },
     {
         bookId:'007', 
         bookName:'伊利亚特',
         isBook:false,
         isBorrow:true,
         author:'荷马'
     },
     {
         bookId:'008', 
         bookName:'社会契约论',
         isBook:true,
         isBorrow:true,
         author:'卢梭'
     },
     {
         bookId:'009', 
         bookName:'历史',
         isBook:false,
         isBorrow:true,
         author:'希罗多德'
     },
     {
         bookId:'010', 
         bookName:'国富论',
         isBook:false,
         isBorrow:false,
         author:'亚当斯密'
     },
     {
         bookId:'011', 
         bookName:'我生活的故事',
         isBook:true,
         isBorrow:false,
         author:'海伦.凯勒'
     },
     {
         bookId:'012', 
         bookName:'傲慢与偏见',
         isBook:false,
         isBorrow:true,
         author:'简.奥古斯汀'
     },
     {
         bookId:'013', 
         bookName:'瓦尔登湖',
         isBook:false,
         isBorrow:true,
         author:'梭罗'
     },
     {
         bookId:'014', 
         bookName:'巴黎圣母院',
         isBook:false,
         isBorrow:false,
         author:'维克多.雨果'
     },
     {
         bookId:'015', 
         bookName:'高老头',
         isBook:true,
         isBorrow:true,
         author:'巴尔扎克'
     },
     {
         bookId:'016', 
         bookName:'法国大革命',
         isBook:false,
         isBorrow:true,
         author:'汤姆士.卡雷尔'
     },
     {
         bookId:'017', 
         bookName:'人口论',
         isBook:true,
         isBorrow:false,
         author:'马尔赛斯'
     },
     {
         bookId:'018', 
         bookName:'伦理学',
         isBook:true,
         isBorrow:true,
         author:'亚里士多德'
     },
     {
         bookId:'019', 
         bookName:'论语',
         isBook:false,
         isBorrow:true,
         author:'孔子'
     },
     {
         bookId:'020', 
         bookName:'史记',
         isBook:false,
         isBorrow:true,
         author:'司马迁'
     },
     {
         bookId:'021', 
         bookName:'世说新语',
         isBook:true,
         isBorrow:true,
         author:'刘义庆'
     },
     {
         bookId:'022', 
         bookName:'三国演义',
         isBook:false,
         isBorrow:true,
         author:'罗贯中'
     },
     {
         bookId:'023', 
         bookName:'西游记',
         isBook:true,
         isBorrow:true,
         author:'吴承恩'
     },
     {
         bookId:'023', 
         bookName:'儒林外史',
         isBook:false,
         isBorrow:false,
         author:'吴敬梓'
     },
     {
         bookId:'024', 
         bookName:'红楼梦',
         isBook:false,
         isBorrow:true,
         author:'曹雪芹'
     },
     {
         bookId:'024', 
         bookName:'聊斋志异',
         isBook:false,
         isBorrow:true,
         author:'蒲松龄'
     },
     {
         bookId:'025', 
         bookName:'家',
         isBook:false,
         isBorrow:true,
         author:'巴金'
     },
     {
         bookId:'026', 
         bookName:'骆驼祥子',
         isBook:false,
         isBorrow:true,
         author:'老舍'
     },
     {
         bookId:'027', 
         bookName:'边城',
         isBook:true,
         isBorrow:true,
         author:'沈从文'
     },
 ]