export interface courseType{
    courseName:string, // 课程 名
    courseId:string, // 课程 编号
    core:number, // 课程分数
    studentId:string, // 选修的学生编号
    isChoose:boolean,// 是否已选修
    isMakeUp:boolean,// 是否申请补考
}
export const courseStore:courseType[] = [
    {
        courseName:"数据结构",
        courseId:'001',
        core:90,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    {
        courseName:"算法分析与设计",
        courseId:'002',
        core:70,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    {
        courseName:"单片机原理与技术",
        courseId:'003',
        core:0,
        studentId:'201910137816',
        isChoose:false,
        isMakeUp:false,
        
    },
    {
        courseName:"网页设计",
        courseId:'004',
        core:57,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    // {
    //     courseName:'高等数学1',
    //     courseId:'005',
    //     core:59,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // },
    {
        courseName:'大学英语1',
        courseId:'006',
        core:70,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    {
        courseName:'大学英语2',
        courseId:'007',
        core:55,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:true,
    },
    {
        courseName:'面向对象程序设计',
        courseId:'008',
        core:65,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    {
        courseName:'程序设计基础',
        courseId:'010',
        core:65,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    // {
    //     courseName:'程序设计基础',
    //     courseId:'011',
    //     core:54,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:false,
    // },
    // {
    //     courseName:'高等数学2',
    //     courseId:'012',
    //     core:59,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // },
    {
        courseName:'思想道德与法治',
        courseId:'013',
        core:65,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:true,
    },
    {
        courseName:'计算机应用基础',
        courseId:'014',
        core:71,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    // {
    //     courseName:'高等数学',
    //     courseId:'015',
    //     core:78,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // },
    // {
    //     courseName:'高等数学',
    //     courseId:'016',
    //     core:77,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // },
    // {
    //     courseName:'大学英语',
    //     courseId:'017',
    //     core:59,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // },
    // {
    //     courseName:'计算机应用基础',
    //     courseId:'018',
    //     core:66,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // },
    // {
    //     courseName:'大学英语',
    //     courseId:'019',
    //     core:77,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:false,
    // },
    // {
    //     courseName:'高等数学',
    //     courseId:'020',
    //     core:60,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // },
    // {
    //     courseName:'大学英语',
    //     courseId:'021',
    //     core:71,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:false,
    // },
    {
        courseName:'高等数学1',
        courseId:'022',
        core:60,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:true,
    },
    {
        courseName:'高等数学2',
        courseId:'023',
        core:63,
        studentId:'201910137816',
        isChoose:true,
        isMakeUp:false,
    },
    // {
    //     courseName:'思想道德与法治',
    //     courseId:'024',
    //     core:70,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:false,
    // },
    // {
    //     courseName:'思想道德与法治',
    //     courseId:'025',
    //     core:72,
    //     studentId:'201910137816',
    //     isChoose:true,
    //     isMakeUp:true,
    // }
]